services:
  ha-fusion:
    container_name: ha-fusion
    build:
      context: .
    volumes:
      - /home/imilka/ha-fusion-fork:/app/data
    network_mode: bridge
    ports:
      - 5051:5051
    environment:
      TZ: Europe/Stockholm
      HASS_URL: http://meow.local:8123
    restart: always
